version:                "3"
services:
  this_jupyter:
      build:
        context: ./docker/jupyter/
        dockerfile: Dockerfile
      volumes:
        - .:/home/jovyan/
      ports:
        - 8888:8888
      container_name:   this_jupyter
